name: Release Action

on:
  push:
    tags:
      - "v*"

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Print env
      run: |
        corepack enable
        echo "go version:" $(go version)
        echo "node version:" $(node -v)
        echo "npm version:" $(npm -v)
        echo "pnpm version:" $(pnpm -v)
    - name: Bootstrap
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        make bootstrap
        echo "go-bindata version:" $(go-bindata -version)
    - name: Build frontend assets
      run: |
        make build-web
        export PATH=$PATH:$(go env GOPATH)/bin
        make build-assets
    - name: Build all arch binary
      run: make build-all-arch
    - name: Upload to Release
      run: |
        make pack-arch TAG=${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: xgheaven/homebox:latest
        context: .
